server:
  port: 8085
  address: 0.0.0.0

spring:
  application:
    name: projectarchiver

  datasource:
    url: jdbc:postgresql://localhost:5432/projectarchiver
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

    access-token:
      expiration: 900000 # 15 minutes

    refresh-token:
      expiration: 86400000 # 1 day

springdoc:
  api-docs:
    path: /v1/api-docs
    enabled: true
  swagger-ui:
    path: /v1/swagger.html
